version: '3'

services:
  app:
    build: ./
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - api
    command: ['sh', '-c', 'yarn start']
    volumes:
      - ./src:/var/www/src
    environment:
      - NODE_ENV=development
      - GRAPHQL_URL=api/graphql/


  api:
    build: ../graphql-api/
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_DB_URI=mongodb://database/test

  mongo-seed:
    build: ../graphql-api/mongo-seed
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
